// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALEu1U3S_8W5BHge9kdnN-79FWdGg96D0',
    appId: '1:844394528658:web:206c3c60a6043dd1e58b4b',
    messagingSenderId: '844394528658',
    projectId: 'braneflow',
    authDomain: 'braneflow.firebaseapp.com',
    storageBucket: 'braneflow.appspot.com',
    measurementId: 'G-QFZB6R00QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsjxm6X-fWv0xLtjqV7YM6c3QxdqZ2rEQ',
    appId: '1:844394528658:android:8e0974589dad9742e58b4b',
    messagingSenderId: '844394528658',
    projectId: 'braneflow',
    storageBucket: 'braneflow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmqLkKQa3bh3PV7cqLpvzNOU1QH6fMhos',
    appId: '1:844394528658:ios:41597ee15aed401ee58b4b',
    messagingSenderId: '844394528658',
    projectId: 'braneflow',
    storageBucket: 'braneflow.appspot.com',
    iosClientId: '844394528658-72niqa2vuk66645md6ofqaod7h0rcebh.apps.googleusercontent.com',
    iosBundleId: 'com.example.templateFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmqLkKQa3bh3PV7cqLpvzNOU1QH6fMhos',
    appId: '1:844394528658:ios:cf1c7d9392e654cee58b4b',
    messagingSenderId: '844394528658',
    projectId: 'braneflow',
    storageBucket: 'braneflow.appspot.com',
    iosClientId: '844394528658-sn9nmtr7a5rtjsuf7hcri8q9o93tr85j.apps.googleusercontent.com',
    iosBundleId: 'com.example.templateFlow.RunnerTests',
  );
}
