name: Build Flutter APK's and App bundle
 
on:
 
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Custom package name for the build'
        required: true
        type: string
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
 
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: '3.13.6'
      - run:
          yes | flutter doctor --android-licenses
          flutter doctor -v
 
      - name: Install Flutter dependencies
        run:
          flutter pub get
 
      - name: Create 'apk' Folder if Not Exist
        run: mkdir -p apk
 
      - name: Use Input Value
        run: |
          PACKAGE_NAME="${{ inputs.package_name }}"
          echo "Using package name provided in workflow dispatch: $PACKAGE_NAME"
          flutter pub run change_app_package_name:main $PACKAGE_NAME
          git add .
          git status
          git branch
          flutter doctor -v
                   
      - name: Build APK
        run: flutter build apk --split-per-abi --release
 
      - name: Move APK Files to 'apk' Folder
        run: mv build/app/outputs/apk/release/*.apk apk/
     
      - name: List Changed Files
        run: git status
 
      - name: List Staged Files
        run: git diff --cached --name-only
 
      - name: Commit APKs to Repository
        run: |
          git config user.name "Coder"
          git config user.email "gitCoder@example.com"
          git add apk/*.apk
          git commit -m "Added Changed APK files"
          git push
